/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    kotlin("jvm") version "1.5.10"
}

repositories {
    mavenCentral()

    maven { setUrl("https://jitpack.io") }

    ivy {
        setUrl("https://download.eclipse.org/tools/cdt/releases/10.2/cdt-10.2.0/plugins")
        metadataSources {
            artifact()
        }
        patternLayout {
            artifact("/[organisation].[module]_[revision].[ext]")
        }
    }
}

dependencies {
    implementation(project(":cpg-solidity"))
}

application {
    // Define the main class for the application.
    mainClass.set("de.fraunhofer.aisec.cpg.AppKt")
}
