# Compiling your contracts...
> Compiling .\contracts\HW.sol Error executing vyper: 'vyper' is not recognized as an internal or external command, operable program or batch file. Truffle v5.1.58 (core: 5.1.58) Node v14.15.1
