contract RandomSVG is ERC721URIStorage, VRFConsumerBase {
    ....
    ....    
    function create() public returns (bytes32 requestId) {
        requestId = requestRandomness(keyhash, fee);
        ...
    ...
    }
 

    function fulfillRandomness(bytes32 requestId, uint256 randomNumber)
        internal
        override
    {
       
    ...
    ...
        _safeMint(nftOwner, tokenId); 
    ...
    }

}
