    Error: ERROR processing C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\deploy\01.js:
    TypeError: contract.fund is not a function
        at Object.module.exports [as func] (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\deploy\01.js:52:26)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at DeploymentsManager.executeDeployScripts (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1219:22)
        at DeploymentsManager.runDeploy (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1052:5)
        at SimpleTaskDefinition.action (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat-deploy\src\index.ts:438:5)
        at Environment._runTaskDefinition (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:14)
        at Environment.run (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat\src\internal\core\runtime-environment.ts:156:14)
        at SimpleTaskDefinition.action (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat-deploy\src\index.ts:584:32)
        at Environment._runTaskDefinition (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:14)
        at Environment.run (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat\src\internal\core\runtime-environment.ts:156:14)
        at DeploymentsManager.executeDeployScripts (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1222:19)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at DeploymentsManager.runDeploy (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1052:5)
        at SimpleTaskDefinition.action (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat-deploy\src\index.ts:438:5)
        at Environment._runTaskDefinition (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:14)
        at Environment.run (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat\src\internal\core\runtime-environment.ts:156:14)
        at SimpleTaskDefinition.action (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat-deploy\src\index.ts:584:32)
        at Environment._runTaskDefinition (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:14)
        at Environment.run (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat\src\internal\core\runtime-environment.ts:156:14)
        at SimpleTaskDefinition.action (C:\Users\ACER\Desktop\Blockchain\JavaScript\HardHat\HardhatFundMe\node_modules\hardhat-deploy\src\index.ts:669:5)
