.code
  PUSH 60           contract Consumer {\n   functi...
  PUSH 40           contract Consumer {\n   functi...
  MSTORE            contract Consumer {\n   functi...
  CALLVALUE             contract Consumer {\n   functi...
  ISZERO            contract Consumer {\n   functi...
  PUSH [tag] 1          contract Consumer {\n   functi...
  JUMPI             contract Consumer {\n   functi...
  PUSH 0            contract Consumer {\n   functi...
  DUP1          contract Consumer {\n   functi...
  REVERT            contract Consumer {\n   functi...
tag 1           contract Consumer {\n   functi...
  JUMPDEST          contract Consumer {\n   functi...
tag 2           contract Consumer {\n   functi...
  JUMPDEST          contract Consumer {\n   functi...
  PUSH #[$] 0000000000000000000000000000000000000000000000000000000000000000            contract Consumer {\n   functi...
  DUP1          contract Consumer {\n   functi...
  PUSH [$] 0000000000000000000000000000000000000000000000000000000000000000         contract Consumer {\n   functi...
  PUSH 0            contract Consumer {\n   functi...
  CODECOPY          contract Consumer {\n   functi...
  PUSH 0            contract Consumer {\n   functi...
  RETURN            contract Consumer {\n   functi...
.data
  0:
    .code
      PUSH 60           contract Consumer {\n   functi...
      PUSH 40           contract Consumer {\n   functi...
      MSTORE            contract Consumer {\n   functi...
      PUSH 0            contract Consumer {\n   functi...
      CALLDATALOAD          contract Consumer {\n   functi...
      PUSH 100000000000000000000000000000000000000000000000000000000            contract Consumer {\n   functi...
      SWAP1             contract Consumer {\n   functi...
      DIV           contract Consumer {\n   functi...
      PUSH FFFFFFFF         contract Consumer {\n   functi...
      AND           contract Consumer {\n   functi...
      DUP1          contract Consumer {\n   functi...
      PUSH 61461954         contract Consumer {\n   functi...
      EQ            contract Consumer {\n   functi...
      PUSH [tag] 2          contract Consumer {\n   functi...
      JUMPI             contract Consumer {\n   functi...
    tag 1           contract Consumer {\n   functi...
      JUMPDEST          contract Consumer {\n   functi...
      PUSH 0            contract Consumer {\n   functi...
      DUP1          contract Consumer {\n   functi...
      REVERT            contract Consumer {\n   functi...
    tag 2           function execute() {\n      ui...
      JUMPDEST          function execute() {\n      ui...
      CALLVALUE             function execute() {\n      ui...
      ISZERO            function execute() {\n      ui...
      PUSH [tag] 3          function execute() {\n      ui...
      JUMPI             function execute() {\n      ui...
      PUSH 0            function execute() {\n      ui...
      DUP1          function execute() {\n      ui...
      REVERT            function execute() {\n      ui...
    tag 3           function execute() {\n      ui...
      JUMPDEST          function execute() {\n      ui...
      PUSH [tag] 4          function execute() {\n      ui...
      PUSH [tag] 5          function execute() {\n      ui...
      JUMP          function execute() {\n      ui...
    tag 4           function execute() {\n      ui...
      JUMPDEST          function execute() {\n      ui...
      STOP          function execute() {\n      ui...
    tag 5           function execute() {\n      ui...
      JUMPDEST          function execute() {\n      ui...
      PUSH 0            uint x
      DUP1          uint y
      PUSHLIB browser/Untitled.sol:A            A
      PUSH 82692679         A.doSomething
      PUSH 0            A.doSomething()
      PUSH 40           A.doSomething()
      MLOAD             A.doSomething()
      PUSH 20           A.doSomething()
      ADD           A.doSomething()
      MSTORE            A.doSomething()
      PUSH 40           A.doSomething()
      MLOAD             A.doSomething()
      DUP2          A.doSomething()
      PUSH FFFFFFFF         A.doSomething()
      AND           A.doSomething()
      PUSH 100000000000000000000000000000000000000000000000000000000            A.doSomething()
      MUL           A.doSomething()
      DUP2          A.doSomething()
      MSTORE            A.doSomething()
      PUSH 4            A.doSomething()
      ADD           A.doSomething()
      PUSH 20           A.doSomething()
      PUSH 40           A.doSomething()
      MLOAD             A.doSomething()
      DUP1          A.doSomething()
      DUP4          A.doSomething()
      SUB           A.doSomething()
      DUP2          A.doSomething()
      DUP7          A.doSomething()
      DUP1          A.doSomething()
      EXTCODESIZE           A.doSomething()
      ISZERO            A.doSomething()
      ISZERO            A.doSomething()
      PUSH [tag] 7          A.doSomething()
      JUMPI             A.doSomething()
      PUSH 0            A.doSomething()
      DUP1          A.doSomething()
      REVERT            A.doSomething()
    tag 7           A.doSomething()
      JUMPDEST          A.doSomething()
      PUSH 2C6          A.doSomething()
      GAS           A.doSomething()
      SUB           A.doSomething()
      DELEGATECALL          A.doSomething()
      ISZERO            A.doSomething()
      ISZERO            A.doSomething()
      PUSH [tag] 8          A.doSomething()
      JUMPI             A.doSomething()
      PUSH 0            A.doSomething()
      DUP1          A.doSomething()
      REVERT            A.doSomething()
    tag 8           A.doSomething()
      JUMPDEST          A.doSomething()
      POP           A.doSomething()
      POP           A.doSomething()
      POP           A.doSomething()
      PUSH 40           A.doSomething()
      MLOAD             A.doSomething()
      DUP1          A.doSomething()
      MLOAD             A.doSomething()
      SWAP1             A.doSomething()
      POP           A.doSomething()
      SWAP2             uint x = A.doSomething()
      POP           uint x = A.doSomething()
      PUSH [tag] 9          A.doInternal()
      PUSH [tag] 10         A.doInternal
      JUMP [in]         A.doInternal()
    tag 9           A.doInternal()
      JUMPDEST          A.doInternal()
      SWAP1             uint y = A.doInternal()
      POP           uint y = A.doInternal()
    tag 6           function execute() {\n      ui...
      JUMPDEST          function execute() {\n      ui...
      POP           function execute() {\n      ui...
      POP           function execute() {\n      ui...
      JUMP [out]            function execute() {\n      ui...
    tag 10          function doInternal() internal...
      JUMPDEST          function doInternal() internal...
      PUSH 0            uint
      PUSH 63           99
      SWAP1             return 99
      POP           return 99
    tag 11          function doInternal() internal...
      JUMPDEST          function doInternal() internal...
      SWAP1             function doInternal() internal...
      JUMP [out]            function doInternal() internal...
    .data
