    function mul(uint256 a, uint256 b) internal pure returns (uint256) {
        ...
        assert(c / a == b);
        ...
    }

    function div(uint256 a, uint256 b) internal pure returns (uint256) {
        ...
        uint256 c = a / b;
        ...
    }

    function sub(uint256 a, uint256 b) internal pure returns (uint256) {
        assert(b <= a);
        ...
    }

    function add(uint256 a, uint256 b) internal pure returns (uint256) {
        ...
        assert(c >= a);
        ...
    }
