event NewMint(uint256 i, string t);

function mintNft() public{
   
   emit NewMint(0, tokenURI(0));
}

function tokenURI(uint256 tokenId) public view override(ERC721, ERC721URIStorage) returns (string memory){
   return "data:application/json;base64,eyJuYW1lIjogIkV2ZXJ5ZGF5IEF2YXRhciAjMCIsICJkZXNjcmlwdGlvbiI6IkV2ZXJ5ZGF5IEF2YXRhcnMgYXJlIGEgY29sbGVjdGlvbiBvZiBwcm9maWxlIHBpY3R1cmUgTkZUcyB0aGF0IGFyZSBjb21wbGV0ZWx5IGN1c3RvbWl6YWJsZS4gWW91IGNhbiBmcmVlbHkgbW9kaWZ5IGFuZCB1cGRhdGUgeW91ciBBdmF0YXIgdXNpbmcgdGhlIGRBcHAuIEF0dHJpYnV0ZXMgYXJlIHN0b3JlZCBvbi1jaGFpbiBhbmQgdGhpcyBhbWF6aW5nIGZsZXhpYmlsaXR5IGlzIHBvd2VyZWQgYnkgRUlQLTM2NjQuIiwgImltYWdlIjoiaHR0cHM6Ly9ldmVyeWRheWF2YXRhcmFwaS5oZXJva3VhcHAuY29tL3ZpZXctYXZhdGFyLzAwNDYwMDA5MDAyNTAwMDAiLCJhdHRyaWJ1dGVzIjpbeyJ0cmFpdF90eXBlIjoiQmFja2dyb3VuZCIsInZhbHVlIjoiRGFyayBHcmV5In0seyJ0cmFpdF90eXBlIjoiSGVhZCIsInZhbHVlIjoiU2FudGEgQ2FwIn0seyJ0cmFpdF90eXBlIjoiRmFjZSIsInZhbHVlIjoiU3VuZ2xhc3NlcyJ9XX0=";
}

