Error: ERROR processing /home/abinash/Desktop/DEX2/deploy/deploy.js:
TypeError: dex.setLiquidity is not a function
    at Object.module.exports [as func] (/home/abinash/Desktop/DEX2/deploy/deploy.js:84:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.executeDeployScripts (/home/abinash/Desktop/DEX2/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)
    at DeploymentsManager.runDeploy (/home/abinash/Desktop/DEX2/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/home/abinash/Desktop/DEX2/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/home/abinash/Desktop/DEX2/node_modules/hardhat/src/internal/core/runtime-environment.ts:311:14)
    at Environment.run (/home/abinash/Desktop/DEX2/node_modules/hardhat/src/internal/core/runtime-environment.ts:159:14)
    at SimpleTaskDefinition.action (/home/abinash/Desktop/DEX2/node_modules/hardhat-deploy/src/index.ts:584:32)
    at Environment._runTaskDefinition (/home/abinash/Desktop/DEX2/node_modules/hardhat/src/internal/core/runtime-environment.ts:311:14)
    at Environment.run (/home/abinash/Desktop/DEX2/node_modules/hardhat/src/internal/core/runtime-environment.ts:159:14)
    at DeploymentsManager.executeDeployScripts (/home/abinash/Desktop/DEX2/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.runDeploy (/home/abinash/Desktop/DEX2/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/home/abinash/Desktop/DEX2/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/home/abinash/Desktop/DEX2/node_modules/hardhat/src/internal/core/runtime-environment.ts:311:14)
    at Environment.run (/home/abinash/Desktop/DEX2/node_modules/hardhat/src/internal/core/runtime-environment.ts:159:14)
    at SimpleTaskDefinition.action (/home/abinash/Desktop/DEX2/node_modules/hardhat-deploy/src/index.ts:584:32)
    at Environment._runTaskDefinition (/home/abinash/Desktop/DEX2/node_modules/hardhat/src/internal/core/runtime-environment.ts:311:14)
    at Environment.run (/home/abinash/Desktop/DEX2/node_modules/hardhat/src/internal/core/runtime-environment.ts:159:14)
    at SimpleTaskDefinition.action (/home/abinash/Desktop/DEX2/node_modules/hardhat-deploy/src/index.ts:669:5)
