bytes32[] public clientIdList;
bytes32[] public caseIdList;

function getClientCount() public view returns(uint count) ...
function getCaseCount() public view returns(uint count) ...
function getClientCaseCount(bytes32 clientId) public view returns(uint count) ...
function getClientCaseAtRow(bytes32 clientId, uint row) public view returns(...
