interface IERC20 { ... 
contract ERC20 is IERC20 { ... 

contract TokenA is ERC20 { ... 
contract TokenB is ERC20 { ...
contract TokenC is ERC20 { ...

contract WorkWithAnyToken {

  
  

  function withFromAny(IERC20 token, uint amount) public ... 
    token.transfer(msg.sender, amount);
  }
}
