const RandomSVGContract = await ethers.getContractFactory('RandomSVG')
const randomSVG = new ethers.Contract(RandomSVG.address, RandomSVGContract.interface, signer)
let creation_tx = await randomSVG.create({ gasLimit: 7000000, gasPrice: 20000000000, value: '1000000000000000000' })
log(`testing 1`)
let receipt = await creation_tx.wait(1)
log(`testing 2`)
let tokenId = receipt.events[3].topics[2]
log(`testing 3`)
log(`You have made your NFT! This is token number ${tokenId.toString()}`)
log(`Lets wait for the ChainLink node to respond...`)
