/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `java-library`
    antlr
    kotlin("jvm") version "1.5.10"
}

repositories {
    mavenCentral()

    maven { setUrl("https://jitpack.io") }

    ivy {
        setUrl("https://download.eclipse.org/tools/cdt/releases/10.2/cdt-10.2.0/plugins")
        metadataSources {
            artifact()
        }
        patternLayout {
            artifact("/[organisation].[module]_[revision].[ext]")
        }
    }
}

val versions = mapOf(
    "junit5" to "5.6.0"
)

dependencies {
    api("com.github.Fraunhofer-AISEC", "cpg", "4.0.0-beta.2")
    antlr("org.antlr:antlr4:4.5")

    testImplementation(kotlin("test"))
    testImplementation("org.junit.jupiter", "junit-jupiter-api", versions["junit5"])
    testImplementation("org.junit.jupiter", "junit-jupiter-params", versions["junit5"])
    testRuntimeOnly("org.junit.jupiter", "junit-jupiter-engine", versions["junit5"])
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    dependsOn("generateGrammarSource")
}

tasks.test {
    useJUnitPlatform()
}
